FROM 10.56.184.75:8000/falcosecurity/falco-no-driver:0.38.1
ADD libk8smeta.so /usr/share/falco/plugins/libk8smeta.so
ADD libk8saudit.so /usr/share/falco/plugins/libk8saudit.so
ADD libjson.so /usr/share/falco/plugins/libjson.so
ADD libk8saudit.so /usr/share/falco/plugins/libk8saudit.so
ADD libjson.so /usr/share/falco/plugins/libjson.so
